development: &development
  :users:
    :image:
      :default_url: '/assets/missing.png'
      :styles:
        :avatar: '150x150>'
      :url: "/todo-app/users/:id/:style/:basename.:extension"
      :path: ":rails_root/public/todo-app/users/:id/:style/:basename.:extension"

production: 
  <<: *development